spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/plusproject
    # url : aws -> end point
    username: ${your_username}
    password: ${your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  mail:
    username: ${your_naver_name}
    password: ${your_naver_password}
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  access-token-expiration: 86400000  # 1시간
  refresh-token-expiration: 8467200000 # 14일
  secret_key: ${jwt.secret_key}
cloud:
  aws:
    s3:
      bucket: ${your_bucket_name}
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${your_accessKey}
      secretKey: ${your_secretKey}